type: map
mapping:
  "name":
    type: str
    required: yes
  "event":
    type: map
    required: yes
    mapping:
      "name":
        type: str
        required: yes
      "arguments":
        type: seq
        sequence:
          - type: str
  "conditions":
    type: seq
    sequence:
      - type: map
        mapping: 
          "type":
            type: str
            required: yes
          "method":
            type: str
            required: yes
          "arguments":
            type: seq
            sequence: 
              - type: any
          "value":
            type: any
  "action":
    type: map
    mapping:
      "name":
        type: str
        required: yes
      "arguments":
        type: seq
        sequence:
          - type: map
            mapping:
              "key":
                type: str
              "val":
                type: any